name: Deploy dev
on:
    push:
        branches: dev
        paths:
            - 'server/**/*'
            - 'public/**/*'
            - '**.js'
            - 'package.json'
            - 'yarn.lock'
            - 'config.json'

jobs:
    Build-Deploy:
        runs-on: 'ubuntu-latest'
        steps:
            -   uses: actions/checkout@v2
            -   name: Install Node.js
                uses: actions/setup-node@v1
                with:
                    node-version: '12.x'
            -   name: Install dependencies
                run: yarn --prod
            -   name: Build
                run: yarn run build
            -   name: Deploy to Server
                uses: easingthemes/ssh-deploy@v2.1.5
                env:
                    SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
                    REMOTE_HOST: ${{ secrets.SSHHOST }}
                    REMOTE_USER: ${{ secrets.SSHUSERNAME }}
                    ARGS: "-rltgoDzvO --delete"
                    SOURCE: "dist/"
                    TARGET: '/home/delta/dev'
            -   name: Restart Process
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.SSHHOST }}
                    username: ${{ secrets.SSHUSERNAME }}
                    password: ${{ secrets.SSHPASSWORD }}
                    script: |
                        pm2 reload /home/delta/ecosystem.config.js --only dev